### ISSUE TITLE
Docs mobile template doesn’t use full page

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit.org#247] opened 2019-10-18 15:16 UTC
Likely just changing the column classes on the two or three doc templates. 

![4C5E7623-36DC-4E63-AE1C-029E521FA29C](https://user-images.githubusercontent.com/20846414/67106455-866de380-f17f-11e9-835e-002cb94f243f.png)

**Comment by matildepark** [comment] 2019-10-18 15:20
Actually looks like it could be all mobile templates. The margin on the right feels like it shouldn’t be so big. Hm.

**Comment by Fang-** [comment] 2019-10-18 17:46
Possible duplicate of #233?

**Closed as completed** 2019-10-21 17:50 UTC
