### ISSUE TITLE
update Understanding Urbit guide

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/urbit.org#1257] opened 2021-11-24 19:13 UTC
The Understanding Urbit guide is out of date, and especially needs to mention
software distribution. It's the only newbie explainer we have on the site. Since
it was previously only available in the footer of the front page, I've added a
link to it in the Getting Started guide #1256.

This supercedes #660.

**Comment by matildepark** [comment] 2022-05-06 00:01
Duplicate of #696

**Closed as completed by matildepark** 2022-05-06 00:01 UTC
