### ISSUE TITLE
Invalid hoon syntax in content

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit.org#240] opened 2019-10-17 16:47 UTC
Where it says `~12m`, that's not valid Hoon.  `~m12` means twelve minutes.  If that looks funny, we should probably just use English.

Sorry for not making a PR, I had trouble finding the file this text came from.

**Comment by matildepark** [comment] 2019-10-17 17:00
You mean on the homepage? To the best of my knowledge it was intended to not be Hoon. But I feel like it should. I'll talk to the copywriter (I think it was @galenwp) and make a call on it.

(And it's `templates/index.html`. Directories and index pages end up getting their content deployed separately as a specialised template, which isn't ideal, but how it is on the static deployment.)

**Comment by galenwp** [comment] 2019-10-17 17:06
I feel like it reads just fine as `~12m` — which I intended to read as 'about twelve minutes'. I was thinking of it more like a twitter-style timestamp.

**Comment by belisarius222** [comment] 2019-10-17 17:20
We generally refrain from using ~some-amount to mean "about", since we
prefix so many things with ~ in technical language.  The fact that it's
also in monospace makes it look even more like code, and the syntax is
almost exactly a Hoon relative date -- so close, it just looks like a
mistake.  We use Hoon syntax for all kinds of things, like Urbit IDs and
dates of blog posts, so using Twitter's relative date format here instead
of our own feels like a somewhat jarring inconsistency.

—
~rovnys-ricfer
https://urbit.org

**Comment by galenwp** [comment] 2019-10-17 17:40
I'm fine to write the whole thing out — I'm not super attached to this. But I do refuse to fix it if it doesn't render properly on your fitbit.

**Comment by matildepark** [comment] 2019-10-17 21:21
Fixed in 1269f8e6b5cc680868a8b72825cbd7ade47f9655.

**Closed as completed by matildepark** 2019-10-17 21:21 UTC
